# Change these first
owner: lakesideminers # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: Red's Server Root
    url: https://redsserver.com
  - name: TheLounge
    url: https://talk.redsserver.com
  - name: TinyTinyRSS
    url: https://rss.redsserver.com
  - name: Wikipedia En
    url: https://en.wikipedia.org
  - name: Zoom Overall
    url: https://status.zoom.us/api/v2/status.json
    __dangerous__body_degraded: "Partial System Outage"
    __dangerous__body_down: "Major Service Outage"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /statuspage
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  theme: dark
  introTitle: "Red's Status."
  introMessage: This is the Status Page for the stuff of my server, just checks what status code is given, and other services I use or need to keep an eye on
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Zoom Status Page
      href: https://14qjgk812kgk.statuspage.io
    - title: Schoology/Powerschool Status Page
      href: https://status.powerschool.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
